export const CODES = {
    //HTTP Response codes
    COD_RESPONSE_HTTP_OK: 200,
    COD_RESPONSE_HTTP_CREATED: 201,
    COD_RESPONSE_HTTP_BAD_REQUEST: 400,
    COD_RESPONSE_HTTP_UNAUTHORIZED: 401,
    COD_RESPONSE_HTTP_FORBIDDEN: 403,
    COD_RESPONSE_HTTP_NOT_FOUND: 404,
    COD_RESPONSE_HTTP_ERROR: 500,
    COD_RESPONSE_HTTP_ACCEPTED: 202,
  };